In [ ]:
from google.colab import files
files.upload()

In [15]:


print(files.upload().keys())

Saving psd_coffee.csv to psd_coffee.csv
dict_keys(['psd_coffee.csv'])

In [16]:
import pandas as pd
import numpy as np

coffee = pd.read_csv("psd_coffee.csv")

population = pd.read_csv(
    "/content/API_SP.POP.TOTL_DS2_EN_csv_v2_3107.csv",
    skiprows=4
)

countries = pd.read_csv(
    "countries-codes (1).csv",
    sep=";"
)

In [18]:
print("="*60)
print("Dataset Shapes")
print("="*60)

print(f"Coffee Dataset      : {coffee.shape}")
print(f"Population Dataset  : {population.shape}")
print(f"Country Codes       : {countries.shape}")

============================================================
Dataset Shapes
============================================================
Coffee Dataset      : (85937, 12)
Population Dataset  : (265, 71)
Country Codes       : (247, 11)

In [19]:
print("Coffee Columns")
display(coffee.columns)

print("\nPopulation Columns")
display(population.columns)

print("\nCountry Code Columns")
display(countries.columns)

Coffee Columns

Index(['Commodity_Code', 'Commodity_Description', 'Country_Code',
       'Country_Name', 'Market_Year', 'Calendar_Year', 'Month', 'Attribute_ID',
       'Attribute_Description', 'Unit_ID', 'Unit_Description', 'Value'],
      dtype='object')

Population Columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', 'Unnamed: 70'],
      dtype='object')

Country Code Columns

Index(['OFFICIAL LANG CODE', 'ISO2 CODE', 'ISO3 CODE', 'ONU CODE',
       'IS ILOMEMBER', 'IS RECEIVING QUEST', 'LABEL EN', 'LABEL FR',
       'LABEL SP', 'Geo Shape', 'geo_point_2d'],
      dtype='object')

In [20]:
print("="*60)
print("Coffee Dataset")
print("="*60)

display(
    coffee[
        ["Country_Name","Country_Code"]
    ].drop_duplicates().head(20)
)

============================================================
Coffee Dataset
============================================================

                   Country_Name Country_Code
0                       Albania           AL
399                     Algeria           AG
855                      Angola           AO
2109                  Argentina           AR
2565                    Armenia           AM
2869                  Australia           AS
3325                      Benin           DM
4370                    Bolivia           BL
5624     Bosnia and Herzegovina           BK
6023                     Brazil           BR
7277                    Burundi           BY
8531                   Cameroon           CM
9785                     Canada           CA
10241  Central African Republic           CT
11495                     Chile           CI
11951                     China           CH
12407                  Colombia           CO
13661       Congo (Brazzaville)           CF
14915          Congo (Kinshasa)           CG
16169                Costa Rica           CS

In [21]:
print("="*60)
print("Population Dataset")
print("="*60)

display(
    population[
        ["Country Name","Country Code"]
    ].head(20)
)

============================================================
Population Dataset
============================================================

                   Country Name Country Code
0                         Aruba          ABW
1   Africa Eastern and Southern          AFE
2                   Afghanistan          AFG
3    Africa Western and Central          AFW
4                        Angola          AGO
5                       Albania          ALB
6                       Andorra          AND
7                    Arab World          ARB
8          United Arab Emirates          ARE
9                     Argentina          ARG
10                      Armenia          ARM
11               American Samoa          ASM
12          Antigua and Barbuda          ATG
13                    Australia          AUS
14                      Austria          AUT
15                   Azerbaijan          AZE
16                      Burundi          BDI
17                      Belgium          BEL
18                        Benin          BEN
19                 Burkina Faso          BFA

In [22]:
print("="*60)
print("Country Codes Dataset")
print("="*60)

display(
    countries[
        ["LABEL EN","ISO2 CODE","ISO3 CODE"]
    ].head(20)
)

============================================================
Country Codes Dataset
============================================================

                                         LABEL EN ISO2 CODE ISO3 CODE
0                                        Colombia        CO       COL
1                                         Iceland        IS       ISL
2                                          Israel        IL       ISR
3                     Falkland Islands (Malvinas)        FK       FLK
4                                         Comoros        KM       COM
5                                        Cameroon        CM       CMR
6                                    Saint Helena        SH       SHN
7                                          Gambia        GM       GMB
8                           Tanzania (Tanganyika)        T1       TZ1
9                                         Somalia        SO       SOM
10                                         France        FR       FRA
11                                       Guernsey        GG       GGY
12                                 Faeroe Islands        FO       FRO
13                                        Ecuador        EC       ECU
14                                        Réunion        RE       REU
15                                  Taiwan, China        TW       TWN
16                                          Gabon        GA       GAB
17                                  United States        US       USA
18  Yugoslavia, The former Socialist Fed. Rep. of        Y3       YU1
19                                      Indonesia        ID       IDN

In [23]:
coffee_set = set(
    coffee["Country_Name"].dropna().unique()
)

population_set = set(
    population["Country Name"].dropna().unique()
)

countrycode_set = set(
    countries["LABEL EN"].dropna().unique()
)

In [24]:
print("="*60)
print("Unique Countries")
print("="*60)

print(f"Coffee Dataset      : {len(coffee_set)}")

print(f"Population Dataset  : {len(population_set)}")

print(f"Country Codes       : {len(countrycode_set)}")

============================================================
Unique Countries
============================================================
Coffee Dataset      : 94
Population Dataset  : 265
Country Codes       : 247

In [25]:
# Countries that match exactly by name

exact_matches = coffee_set.intersection(population_set)

print("="*60)
print("Exact Matches")
print("="*60)

print(f"Total Exact Matches: {len(exact_matches)}")

============================================================
Exact Matches
============================================================
Total Exact Matches: 81

In [26]:
# Coffee countries NOT found in Population

coffee_not_population = coffee_set - population_set

print("="*60)
print("Coffee Countries NOT Found in Population")
print("="*60)

for country in sorted(coffee_not_population):
    print(country)

============================================================
Coffee Countries NOT Found in Population
============================================================
Congo (Brazzaville)
Congo (Kinshasa)
Egypt
Iran
Korea, South
Laos
Russia
Taiwan
Turkey
Venezuela
Vietnam
Yemen
Yemen (Sanaa)

In [27]:
# Coffee countries NOT found in Country Codes

coffee_not_countrycodes = coffee_set - countrycode_set

print("="*60)
print("Coffee Countries NOT Found in Country Codes")
print("="*60)

for country in sorted(coffee_not_countrycodes):
    print(country)

============================================================
Coffee Countries NOT Found in Country Codes
============================================================
Congo (Brazzaville)
Congo (Kinshasa)
Cote d'Ivoire
European Union
Iran
Korea, South
Laos
North Macedonia
Russia
Taiwan
Tanzania
Venezuela
Vietnam
Yemen (Sanaa)

In [28]:
mismatches = sorted(coffee_not_population)

print(mismatches)

['Congo (Brazzaville)', 'Congo (Kinshasa)', 'Egypt', 'Iran', 'Korea, South', 'Laos', 'Russia', 'Taiwan', 'Turkey', 'Venezuela', 'Vietnam', 'Yemen', 'Yemen (Sanaa)']

In [35]:
def search_population(keyword):
    return population[
        population["Country Name"]
        .str.contains(keyword, case=False, na=False)
    ][["Country Name", "Country Code"]]

        Country Name Country Code
67  Egypt, Arab Rep.          EGY

In [36]:
search_population("viet")
search_population("russ")
search_population("iran")
search_population("vene")
search_population("tur")
search_population("egy")

        Country Name Country Code
67  Egypt, Arab Rep.          EGY

In [37]:
keywords = [
    "congo",
    "egy",
    "iran",
    "korea",
    "lao",
    "russ",
    "tai",
    "tur",
    "vene",
    "viet",
    "yemen"
]

for word in keywords:

    print("="*60)
    print(word.upper())
    print("="*60)

    display(
        population[
            population["Country Name"]
            .str.contains(word, case=False, na=False)
        ][["Country Name","Country Code"]]
    )

============================================================
CONGO
============================================================

        Country Name Country Code
43  Congo, Dem. Rep.          COD
44       Congo, Rep.          COG

============================================================
EGY
============================================================

        Country Name Country Code
67  Egypt, Arab Rep.          EGY

============================================================
IRAN
============================================================

           Country Name Country Code
111  Iran, Islamic Rep.          IRN

============================================================
KOREA
============================================================

                  Country Name Country Code
125                Korea, Rep.          KOR
192  Korea, Dem. People's Rep.          PRK

============================================================
LAO
============================================================

    Country Name Country Code
128      Lao PDR          LAO

============================================================
RUSS
============================================================

           Country Name Country Code
31    Brunei Darussalam          BRN
201  Russian Federation          RUS

============================================================
TAI
============================================================

Empty DataFrame
Columns: [Country Name, Country Code]
Index: []

============================================================
TUR
============================================================

                 Country Name Country Code
227  Turks and Caicos Islands          TCA
234              Turkmenistan          TKM
243                   Turkiye          TUR

============================================================
VENE
============================================================

      Country Name Country Code
253  Venezuela, RB          VEN

============================================================
VIET
============================================================

    Country Name Country Code
256     Viet Nam          VNM

============================================================
YEMEN
============================================================

    Country Name Country Code
261  Yemen, Rep.          YEM

In [38]:
countries[
    countries["LABEL EN"]
    .str.contains("tai", case=False, na=False)
][["LABEL EN","ISO2 CODE","ISO3 CODE"]]

         LABEL EN ISO2 CODE ISO3 CODE
15  Taiwan, China        TW       TWN

In [40]:
coffee[
    coffee["Country_Name"]
    .str.contains("Yemen", case=False, na=False)
][["Country_Name","Market_Year","Attribute_Description","Value"]].head(20)

      Country_Name  Market_Year   Attribute_Description  Value
82175        Yemen         1991      Arabica Production   65.0
82176        Yemen         1991            Bean Exports   54.0
82177        Yemen         1991            Bean Imports    0.0
82178        Yemen         1991        Beginning Stocks    0.0
82179        Yemen         1991    Domestic Consumption   10.0
82180        Yemen         1991           Ending Stocks    0.0
82181        Yemen         1991                 Exports   55.0
82182        Yemen         1991                 Imports    0.0
82183        Yemen         1991        Other Production    0.0
82184        Yemen         1991              Production   65.0
82185        Yemen         1991  Roast & Ground Exports    1.0
82186        Yemen         1991  Roast & Ground Imports    0.0
82187        Yemen         1991      Robusta Production    0.0
82188        Yemen         1991  Rst,Ground Dom. Consum   10.0
82189        Yemen         1991      Soluble Dom. Cons.    0.0
82190        Yemen         1991         Soluble Exports    0.0
82191        Yemen         1991         Soluble Imports    0.0
82192        Yemen         1991      Total Distribution   65.0
82193        Yemen         1991            Total Supply   65.0
82194        Yemen         1992      Arabica Production   65.0

In [41]:
coffee[
    coffee["Country_Name"] == "Yemen (Sanaa)"
][["Country_Name", "Market_Year", "Attribute_Description", "Value"]].head(20)

        Country_Name  Market_Year   Attribute_Description  Value
82840  Yemen (Sanaa)         1960      Arabica Production   90.0
82841  Yemen (Sanaa)         1960            Bean Exports   80.0
82842  Yemen (Sanaa)         1960            Bean Imports    0.0
82843  Yemen (Sanaa)         1960        Beginning Stocks    0.0
82844  Yemen (Sanaa)         1960    Domestic Consumption   10.0
82845  Yemen (Sanaa)         1960           Ending Stocks    0.0
82846  Yemen (Sanaa)         1960                 Exports   80.0
82847  Yemen (Sanaa)         1960                 Imports    0.0
82848  Yemen (Sanaa)         1960        Other Production    0.0
82849  Yemen (Sanaa)         1960              Production   90.0
82850  Yemen (Sanaa)         1960  Roast & Ground Exports    0.0
82851  Yemen (Sanaa)         1960  Roast & Ground Imports    0.0
82852  Yemen (Sanaa)         1960      Robusta Production    0.0
82853  Yemen (Sanaa)         1960  Rst,Ground Dom. Consum   10.0
82854  Yemen (Sanaa)         1960      Soluble Dom. Cons.    0.0
82855  Yemen (Sanaa)         1960         Soluble Exports    0.0
82856  Yemen (Sanaa)         1960         Soluble Imports    0.0
82857  Yemen (Sanaa)         1960      Total Distribution   90.0
82858  Yemen (Sanaa)         1960            Total Supply   90.0
82859  Yemen (Sanaa)         1961      Arabica Production   90.0

In [ ]:
# Coffee Dataset Deep Dive

In this section, we analyze the coffee dataset to understand:

- Dataset grain
- Available business attributes
- Time coverage
- Units of measurement
- Data quality

In [42]:
print("="*70)
print("Coffee Dataset Information")
print("="*70)

coffee.info()

======================================================================
Coffee Dataset Information
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85937 entries, 0 to 85936
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Commodity_Code         85937 non-null  int64
 1   Commodity_Description  85937 non-null  object
 2   Country_Code           85937 non-null  object
 3   Country_Name           85937 non-null  object
 4   Market_Year            85937 non-null  int64
 5   Calendar_Year          85937 non-null  int64
 6   Month                  85937 non-null  int64
 7   Attribute_ID           85937 non-null  int64
 8   Attribute_Description  85937 non-null  object
 9   Unit_ID                85937 non-null  int64
 10  Unit_Description       85937 non-null  object
 11  Value                  85937 non-null  float64
dtypes: float64(1), int64(6), object(5)
memory usage: 7.9+ MB

In [43]:
print("="*70)
print("Unique Coffee Attributes")
print("="*70)

attributes = sorted(coffee["Attribute_Description"].unique())

for i, attribute in enumerate(attributes, start=1):
    print(f"{i}. {attribute}")

print("\nTotal Attributes:", len(attributes))

======================================================================
Unique Coffee Attributes
======================================================================
1. Arabica Production
2. Bean Exports
3. Bean Imports
4. Beginning Stocks
5. Domestic Consumption
6. Ending Stocks
7. Exports
8. Imports
9. Other Production
10. Production
11. Roast & Ground Exports
12. Roast & Ground Imports
13. Robusta Production
14. Rst,Ground Dom. Consum
15. Soluble Dom. Cons.
16. Soluble Exports
17. Soluble Imports
18. Total Distribution
19. Total Supply

Total Attributes: 19

In [44]:
print("="*70)
print("Units Used")
print("="*70)

display(
    coffee[
        ["Unit_ID","Unit_Description"]
    ].drop_duplicates()
)

======================================================================
Units Used
======================================================================

   Unit_ID   Unit_Description
0        2  (1000 60 KG BAGS)

In [47]:
print("="*70)
print("Market Year Range")
print("="*70)

print("Minimum Year:", coffee["Market_Year"].min())
print("Maximum Year:", coffee["Market_Year"].max())

print("="*70)
print("Calendar Year Range")
print("="*70)

print("Minimum:", coffee["Calendar_Year"].min())
print("Maximum:", coffee["Calendar_Year"].max())

print("="*70)
print("Months")
print("="*70)

print(sorted(coffee["Month"].unique()))

======================================================================
Market Year Range
======================================================================
Minimum Year: 1960
Maximum Year: 2025
======================================================================
Calendar Year Range
======================================================================
Minimum: 1960
Maximum: 2025
======================================================================
Months
======================================================================
[np.int64(0), np.int64(6), np.int64(12)]

In [48]:
print("="*70)
print("Attribute Frequency")
print("="*70)

display(
    coffee["Attribute_Description"]
    .value_counts()
)

======================================================================
Attribute Frequency
======================================================================

Attribute_Description
Arabica Production        4523
Bean Exports              4523
Bean Imports              4523
Beginning Stocks          4523
Domestic Consumption      4523
Ending Stocks             4523
Exports                   4523
Imports                   4523
Other Production          4523
Production                4523
Roast & Ground Exports    4523
Roast & Ground Imports    4523
Robusta Production        4523
Rst,Ground Dom. Consum    4523
Soluble Dom. Cons.        4523
Soluble Exports           4523
Soluble Imports           4523
Total Distribution        4523
Total Supply              4523
Name: count, dtype: int64

In [49]:
coffee[
    coffee["Country_Name"] == "India"
].head(30)

,Commodity_Code,Commodity_Description,Country_Code,Country_Name,Market_Year,Calendar_Year,Month,Attribute_ID,Attribute_Description,Unit_ID,Unit_Description,Value
36708,711100,"Coffee, Green",IN,India,1960,1960,0,29,Arabica Production,2,(1000 60 KG BAGS),710.0
36709,711100,"Coffee, Green",IN,India,1960,1960,0,90,Bean Exports,2,(1000 60 KG BAGS),527.0
36710,711100,"Coffee, Green",IN,India,1960,1960,0,58,Bean Imports,2,(1000 60 KG BAGS),0.0
36711,711100,"Coffee, Green",IN,India,1960,1960,0,20,Beginning Stocks,2,(1000 60 KG BAGS),436.0
36712,711100,"Coffee, Green",IN,India,1960,1960,0,125,Domestic Consumption,2,(1000 60 KG BAGS),682.0
36713,711100,"Coffee, Green",IN,India,1960,1960,0,176,Ending Stocks,2,(1000 60 KG BAGS),452.0
36714,711100,"Coffee, Green",IN,India,1960,1960,0,88,Exports,2,(1000 60 KG BAGS),527.0
36715,711100,"Coffee, Green",IN,India,1960,1960,0,57,Imports,2,(1000 60 KG BAGS),0.0
36716,711100,"Coffee, Green",IN,India,1960,1960,0,56,Other Production,2,(1000 60 KG BAGS),0.0
36717,711100,"Coffee, Green",IN,India,1960,1960,0,28,Production,2,(1000 60 KG BAGS),1225.0
36718,711100,"Coffee, Green",IN,India,1960,1960,0,107,Roast & Ground Exports,2,(1000 60 KG BAGS),0.0
36719,711100,"Coffee, Green",IN,India,1960,1960,0,75,Roast & Ground Imports,2,(1000 60 KG BAGS),0.0
36720,711100,"Coffee, Green",IN,India,1960,1960,0,53,Robusta Production,2,(1000 60 KG BAGS),515.0
36721,711100,"Coffee, Green",IN,India,1960,1960,0,141,"Rst,Ground Dom. Consum",2,(1000 60 KG BAGS),647.0
36722,711100,"Coffee, Green",IN,India,1960,1960,0,154,Soluble Dom. Cons.,2,(1000 60 KG BAGS),35.0
36723,711100,"Coffee, Green",IN,India,1960,1960,0,114,Soluble Exports,2,(1000 60 KG BAGS),0.0
36724,711100,"Coffee, Green",IN,India,1960,1960,0,82,Soluble Imports,2,(1000 60 KG BAGS),0.0
36725,711100,"Coffee, Green",IN,India,1960,1960,0,178,Total Distribution,2,(1000 60 KG BAGS),1661.0
36726,711100,"Coffee, Green",IN,India,1960,1960,0,86,Total Supply,2,(1000 60 KG BAGS),1661.0
36727,711100,"Coffee, Green",IN,India,1961,1961,0,29,Arabica Production,2,(1000 60 KG BAGS),489.0
36728,711100,"Coffee, Green",IN,India,1961,1961,0,90,Bean Exports,2,(1000 60 KG BAGS),343.0
36729,711100,"Coffee, Green",IN,India,1961,1961,0,58,Bean Imports,2,(1000 60 KG BAGS),0.0
36730,711100,"Coffee, Green",IN,India,1961,1961,0,20,Beginning Stocks,2,(1000 60 KG BAGS),452.0
36731,711100,"Coffee, Green",IN,India,1961,1961,0,125,Domestic Consumption,2,(1000 60 KG BAGS),610.0
36732,711100,"Coffee, Green",IN,India,1961,1961,0,176,Ending Stocks,2,(1000 60 KG BAGS),268.0
36733,711100,"Coffee, Green",IN,India,1961,1961,0,88,Exports,2,(1000 60 KG BAGS),343.0
36734,711100,"Coffee, Green",IN,India,1961,1961,0,57,Imports,2,(1000 60 KG BAGS),0.0
36735,711100,"Coffee, Green",IN,India,1961,1961,0,56,Other Production,2,(1000 60 KG BAGS),0.0
36736,711100,"Coffee, Green",IN,India,1961,1961,0,28,Production,2,(1000 60 KG BAGS),769.0
36737,711100,"Coffee, Green",IN,India,1961,1961,0,107,Roast & Ground Exports,2,(1000 60 KG BAGS),0.0